"""empty message

Revision ID: 19c3d8dba24b
Revises: 
Create Date: 2021-03-03 21:47:25.998724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c3d8dba24b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_USER',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_user')
    )
    op.create_table('T_GARMENT',
    sa.Column('id_garment', sa.Integer(), nullable=False),
    sa.Column('garment_name', sa.String(length=100), nullable=True),
    sa.Column('garment_type', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['T_USER.id_user'], ),
    sa.PrimaryKeyConstraint('id_garment')
    )
    op.create_table('T_MOOD',
    sa.Column('id_mood', sa.Integer(), nullable=False),
    sa.Column('mood_name', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['T_USER.id_user'], ),
    sa.PrimaryKeyConstraint('id_mood')
    )
    op.create_table('T_OUTFIT',
    sa.Column('id_outfit', sa.Integer(), nullable=False),
    sa.Column('outfit_name', sa.String(length=100), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['T_USER.id_user'], ),
    sa.PrimaryKeyConstraint('id_outfit')
    )
    op.create_table('T_GARMENT_X_MOOD',
    sa.Column('id_garment_x_mood', sa.Integer(), nullable=False),
    sa.Column('id_garment', sa.Integer(), nullable=True),
    sa.Column('id_mood', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_garment'], ['T_GARMENT.id_garment'], ),
    sa.ForeignKeyConstraint(['id_mood'], ['T_MOOD.id_mood'], ),
    sa.PrimaryKeyConstraint('id_garment_x_mood')
    )
    op.create_table('T_OUTFIT_X_GARMENT',
    sa.Column('id_outfit_x_garment', sa.Integer(), nullable=False),
    sa.Column('id_outfit', sa.Integer(), nullable=True),
    sa.Column('id_garment', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_garment'], ['T_GARMENT.id_garment'], ),
    sa.ForeignKeyConstraint(['id_outfit'], ['T_OUTFIT.id_outfit'], ),
    sa.PrimaryKeyConstraint('id_outfit_x_garment')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_OUTFIT_X_GARMENT')
    op.drop_table('T_GARMENT_X_MOOD')
    op.drop_table('T_OUTFIT')
    op.drop_table('T_MOOD')
    op.drop_table('T_GARMENT')
    op.drop_table('T_USER')
    # ### end Alembic commands ###
